import { Lead, SearchParams, SearchResult } from '@/types/lead'
import { calculateLeadScore } from '@/lib/scoring'

const MOCK_BUSINESSES: Omit<Lead, 'leadScore' | 'status' | 'notes'>[] = [
  // ── Restaurants ─────────────────────────────────────────────────────────────
  {
    id: '1',
    businessName: "Tony's Pizza & Pasta",
    category: 'Restaurants',
    address: '142 W 42nd St',
    city: 'New York',
    state: 'NY',
    zipCode: '10036',
    phone: '(212) 555-0142',
    website: '',
    rating: 4.2,
    reviewCount: 87,
    latitude: 40.758,
    longitude: -73.9855,
    distanceMiles: 2.3,
    savedAt: undefined,
    createdAt: new Date().toISOString(),
  },
  {
    id: '2',
    businessName: 'Golden Dragon Chinese Bistro',
    category: 'Restaurants',
    address: '3312 N Clark St',
    city: 'Chicago',
    state: 'IL',
    zipCode: '60657',
    phone: '(773) 555-0298',
    website: 'https://goldendragonchicago.com',
    rating: 3.8,
    reviewCount: 45,
    latitude: 41.9435,
    longitude: -87.6432,
    distanceMiles: 4.1,
    savedAt: undefined,
    createdAt: new Date().toISOString(),
  },
  {
    id: '3',
    businessName: 'Sunrise Café & Bakery',
    category: 'Restaurants',
    address: '8801 W Sunset Blvd',
    city: 'Los Angeles',
    state: 'CA',
    zipCode: '90069',
    phone: '(310) 555-0317',
    website: '',
    rating: 4.6,
    reviewCount: 213,
    latitude: 34.0901,
    longitude: -118.3872,
    distanceMiles: 1.7,
    savedAt: undefined,
    createdAt: new Date().toISOString(),
  },
  {
    id: '4',
    businessName: 'The Smoke Pit BBQ',
    category: 'Restaurants',
    address: '5544 Richmond Ave',
    city: 'Houston',
    state: 'TX',
    zipCode: '77057',
    phone: '(713) 555-0441',
    website: 'https://smokepitbbq.com',
    rating: 4.4,
    reviewCount: 178,
    latitude: 29.7355,
    longitude: -95.5035,
    distanceMiles: 6.8,
    savedAt: undefined,
    createdAt: new Date().toISOString(),
  },

  // ── Dentists ────────────────────────────────────────────────────────────────
  {
    id: '5',
    businessName: 'Bright Smile Dental Group',
    category: 'Dentists',
    address: '220 E 42nd St, Suite 810',
    city: 'New York',
    state: 'NY',
    zipCode: '10017',
    phone: '(212) 555-0521',
    website: '',
    rating: 4.7,
    reviewCount: 134,
    latitude: 40.7517,
    longitude: -73.9755,
    distanceMiles: 3.2,
    savedAt: undefined,
    createdAt: new Date().toISOString(),
  },
  {
    id: '6',
    businessName: 'Phoenix Family Dentistry',
    category: 'Dentists',
    address: '2122 E Highland Ave',
    city: 'Phoenix',
    state: 'AZ',
    zipCode: '85016',
    phone: '(602) 555-0612',
    website: 'https://phoenixfamilydentistry.com',
    rating: 4.5,
    reviewCount: 89,
    latitude: 33.5095,
    longitude: -112.0296,
    distanceMiles: 5.5,
    savedAt: undefined,
    createdAt: new Date().toISOString(),
  },
  {
    id: '7',
    businessName: 'Atlanta Smiles Orthodontics',
    category: 'Dentists',
    address: '3350 Peachtree Rd NE',
    city: 'Atlanta',
    state: 'GA',
    zipCode: '30326',
    phone: '(404) 555-0733',
    website: '',
    rating: 4.3,
    reviewCount: 62,
    latitude: 33.8485,
    longitude: -84.3646,
    distanceMiles: 8.2,
    savedAt: undefined,
    createdAt: new Date().toISOString(),
  },

  // ── Plumbers ────────────────────────────────────────────────────────────────
  {
    id: '8',
    businessName: 'Ace Plumbing & Drain Services',
    category: 'Plumbers',
    address: '7721 S Halsted St',
    city: 'Chicago',
    state: 'IL',
    zipCode: '60620',
    phone: '(312) 555-0821',
    website: '',
    rating: 4.1,
    reviewCount: 38,
    latitude: 41.7585,
    longitude: -87.6468,
    distanceMiles: 9.4,
    savedAt: undefined,
    createdAt: new Date().toISOString(),
  },
  {
    id: '9',
    businessName: 'QuickFix Plumbing LLC',
    category: 'Plumbers',
    address: '4401 Westheimer Rd',
    city: 'Houston',
    state: 'TX',
    zipCode: '77027',
    phone: '(713) 555-0944',
    website: 'https://quickfixplumbingtx.com',
    rating: 3.9,
    reviewCount: 27,
    latitude: 29.7377,
    longitude: -95.4627,
    distanceMiles: 11.3,
    savedAt: undefined,
    createdAt: new Date().toISOString(),
  },
  {
    id: '10',
    businessName: 'Desert Flow Plumbing Co.',
    category: 'Plumbers',
    address: '9150 N 43rd Ave',
    city: 'Phoenix',
    state: 'AZ',
    zipCode: '85051',
    phone: '(602) 555-1022',
    website: '',
    rating: 4.0,
    reviewCount: 14,
    latitude: 33.5621,
    longitude: -112.1265,
    distanceMiles: 7.6,
    savedAt: undefined,
    createdAt: new Date().toISOString(),
  },

  // ── Contractors ─────────────────────────────────────────────────────────────
  {
    id: '11',
    businessName: 'Apex Home Remodeling',
    category: 'Contractors',
    address: '1450 Lincoln Blvd',
    city: 'Los Angeles',
    state: 'CA',
    zipCode: '90291',
    phone: '(310) 555-1145',
    website: 'https://apexhomela.com',
    rating: 4.8,
    reviewCount: 301,
    latitude: 33.9917,
    longitude: -118.4507,
    distanceMiles: 3.4,
    savedAt: undefined,
    createdAt: new Date().toISOString(),
  },
  {
    id: '12',
    businessName: 'Steel & Stone General Contracting',
    category: 'Contractors',
    address: '2240 Peachtree Rd NW',
    city: 'Atlanta',
    state: 'GA',
    zipCode: '30309',
    phone: '(404) 555-1267',
    website: '',
    rating: 4.2,
    reviewCount: 55,
    latitude: 33.8033,
    longitude: -84.3933,
    distanceMiles: 6.1,
    savedAt: undefined,
    createdAt: new Date().toISOString(),
  },
  {
    id: '13',
    businessName: 'Mile High Builders LLC',
    category: 'Contractors',
    address: '3210 Larimer St',
    city: 'Denver',
    state: 'CO',
    zipCode: '80205',
    phone: '(720) 555-1322',
    website: '',
    rating: 3.7,
    reviewCount: 19,
    latitude: 39.7596,
    longitude: -104.9764,
    distanceMiles: 4.9,
    savedAt: undefined,
    createdAt: new Date().toISOString(),
  },

  // ── Hair & Beauty Salons ─────────────────────────────────────────────────────
  {
    id: '14',
    businessName: 'Luxe Hair Studio',
    category: 'Hair & Beauty Salons',
    address: '540 Madison Ave',
    city: 'New York',
    state: 'NY',
    zipCode: '10022',
    phone: '(212) 555-1443',
    website: 'https://luxehairstudionyc.com',
    rating: 4.9,
    reviewCount: 287,
    latitude: 40.7589,
    longitude: -73.9726,
    distanceMiles: 1.2,
    savedAt: undefined,
    createdAt: new Date().toISOString(),
  },
  {
    id: '15',
    businessName: 'Bella Vista Salon & Spa',
    category: 'Hair & Beauty Salons',
    address: '6222 N 16th St',
    city: 'Phoenix',
    state: 'AZ',
    zipCode: '85016',
    phone: '(602) 555-1558',
    website: '',
    rating: 4.4,
    reviewCount: 112,
    latitude: 33.5394,
    longitude: -112.0708,
    distanceMiles: 2.8,
    savedAt: undefined,
    createdAt: new Date().toISOString(),
  },
  {
    id: '16',
    businessName: 'Glam & Go Blowout Bar',
    category: 'Hair & Beauty Salons',
    address: '1822 M St NW',
    city: 'Atlanta',
    state: 'GA',
    zipCode: '30309',
    phone: '(404) 555-1634',
    website: '',
    rating: 3.6,
    reviewCount: 8,
    latitude: 33.7908,
    longitude: -84.3878,
    distanceMiles: 14.7,
    savedAt: undefined,
    createdAt: new Date().toISOString(),
  },

  // ── Gyms & Fitness ──────────────────────────────────────────────────────────
  {
    id: '17',
    businessName: 'Iron Works Fitness Center',
    category: 'Gyms & Fitness',
    address: '4455 W Lake St',
    city: 'Chicago',
    state: 'IL',
    zipCode: '60624',
    phone: '(773) 555-1755',
    website: 'https://ironworkschicago.com',
    rating: 4.3,
    reviewCount: 145,
    latitude: 41.886,
    longitude: -87.7302,
    distanceMiles: 5.3,
    savedAt: undefined,
    createdAt: new Date().toISOString(),
  },
  {
    id: '18',
    businessName: 'SunPeak CrossFit',
    category: 'Gyms & Fitness',
    address: '10110 E Camelback Rd',
    city: 'Phoenix',
    state: 'AZ',
    zipCode: '85018',
    phone: '(602) 555-1899',
    website: '',
    rating: 4.7,
    reviewCount: 73,
    latitude: 33.5086,
    longitude: -111.9987,
    distanceMiles: 3.7,
    savedAt: undefined,
    createdAt: new Date().toISOString(),
  },
  {
    id: '19',
    businessName: 'Southside Yoga & Wellness',
    category: 'Gyms & Fitness',
    address: '921 Marietta St NW',
    city: 'Atlanta',
    state: 'GA',
    zipCode: '30318',
    phone: '(404) 555-1966',
    website: '',
    rating: 4.5,
    reviewCount: 48,
    latitude: 33.7722,
    longitude: -84.4072,
    distanceMiles: 10.1,
    savedAt: undefined,
    createdAt: new Date().toISOString(),
  },

  // ── Auto Shops ──────────────────────────────────────────────────────────────
  {
    id: '20',
    businessName: "Rivera's Auto & Tire",
    category: 'Auto Shops',
    address: '2030 E Olympic Blvd',
    city: 'Los Angeles',
    state: 'CA',
    zipCode: '90021',
    phone: '(323) 555-2042',
    website: '',
    rating: 4.1,
    reviewCount: 91,
    latitude: 34.0228,
    longitude: -118.2299,
    distanceMiles: 7.8,
    savedAt: undefined,
    createdAt: new Date().toISOString(),
  },
  {
    id: '21',
    businessName: 'Dallas Precision Auto Repair',
    category: 'Auto Shops',
    address: '7800 N Central Expy',
    city: 'Dallas',
    state: 'TX',
    zipCode: '75225',
    phone: '(214) 555-2133',
    website: 'https://dallaspronauto.com',
    rating: 4.6,
    reviewCount: 203,
    latitude: 32.8655,
    longitude: -96.7836,
    distanceMiles: 5.5,
    savedAt: undefined,
    createdAt: new Date().toISOString(),
  },

  // ── Real Estate Agents ──────────────────────────────────────────────────────
  {
    id: '22',
    businessName: 'Skyline Realty Group',
    category: 'Real Estate Agents',
    address: '350 Fifth Ave, Suite 4900',
    city: 'New York',
    state: 'NY',
    zipCode: '10118',
    phone: '(212) 555-2244',
    website: 'https://skylinerealtyny.com',
    rating: 4.3,
    reviewCount: 67,
    latitude: 40.7484,
    longitude: -73.9967,
    distanceMiles: 2.9,
    savedAt: undefined,
    createdAt: new Date().toISOString(),
  },
  {
    id: '23',
    businessName: 'Emerald City Properties',
    category: 'Real Estate Agents',
    address: '1420 5th Ave',
    city: 'Seattle',
    state: 'WA',
    zipCode: '98101',
    phone: '(206) 555-2311',
    website: '',
    rating: 4.0,
    reviewCount: 33,
    latitude: 47.6082,
    longitude: -122.3351,
    distanceMiles: 4.4,
    savedAt: undefined,
    createdAt: new Date().toISOString(),
  },

  // ── Cleaning Services ────────────────────────────────────────────────────────
  {
    id: '24',
    businessName: 'Sparkle Pro Cleaning',
    category: 'Cleaning Services',
    address: '1901 S Michigan Ave',
    city: 'Chicago',
    state: 'IL',
    zipCode: '60616',
    phone: '(312) 555-2488',
    website: '',
    rating: 4.8,
    reviewCount: 159,
    latitude: 41.8546,
    longitude: -87.6236,
    distanceMiles: 1.8,
    savedAt: undefined,
    createdAt: new Date().toISOString(),
  },
  {
    id: '25',
    businessName: 'Miami Maids Residential Cleaning',
    category: 'Cleaning Services',
    address: '800 Brickell Ave',
    city: 'Miami',
    state: 'FL',
    zipCode: '33131',
    phone: '(305) 555-2567',
    website: 'https://miamimaids.com',
    rating: 4.2,
    reviewCount: 44,
    latitude: 25.7617,
    longitude: -80.1918,
    distanceMiles: 6.6,
    savedAt: undefined,
    createdAt: new Date().toISOString(),
  },

  // ── Photographers ────────────────────────────────────────────────────────────
  {
    id: '26',
    businessName: 'Golden Hour Photography Studio',
    category: 'Photographers',
    address: '3105 Glendale Blvd',
    city: 'Los Angeles',
    state: 'CA',
    zipCode: '90039',
    phone: '(323) 555-2688',
    website: '',
    rating: 4.9,
    reviewCount: 76,
    latitude: 34.1126,
    longitude: -118.2742,
    distanceMiles: 8.3,
    savedAt: undefined,
    createdAt: new Date().toISOString(),
  },
  {
    id: '27',
    businessName: 'Captured Moments Photography',
    category: 'Photographers',
    address: '512 Cherry St NE',
    city: 'Atlanta',
    state: 'GA',
    zipCode: '30307',
    phone: '(404) 555-2741',
    website: 'https://capturedmomentsatl.com',
    rating: 4.6,
    reviewCount: 52,
    latitude: 33.7635,
    longitude: -84.3477,
    distanceMiles: 12.5,
    savedAt: undefined,
    createdAt: new Date().toISOString(),
  },

  // ── HVAC Services ────────────────────────────────────────────────────────────
  {
    id: '28',
    businessName: 'Cool Breeze HVAC & Refrigeration',
    category: 'HVAC Services',
    address: '2800 W Thunderbird Rd',
    city: 'Phoenix',
    state: 'AZ',
    zipCode: '85053',
    phone: '(602) 555-2833',
    website: '',
    rating: 4.4,
    reviewCount: 97,
    latitude: 33.5997,
    longitude: -112.1395,
    distanceMiles: 3.2,
    savedAt: undefined,
    createdAt: new Date().toISOString(),
  },
  {
    id: '29',
    businessName: 'Rockies Heating & Air',
    category: 'HVAC Services',
    address: '1560 Blake St',
    city: 'Denver',
    state: 'CO',
    zipCode: '80202',
    phone: '(303) 555-2912',
    website: 'https://rockieshvac.com',
    rating: 3.5,
    reviewCount: 21,
    latitude: 39.7523,
    longitude: -104.9961,
    distanceMiles: 9.0,
    savedAt: undefined,
    createdAt: new Date().toISOString(),
  },

  // ── Landscaping ──────────────────────────────────────────────────────────────
  {
    id: '30',
    businessName: 'Green Thumb Lawn & Landscape',
    category: 'Landscaping',
    address: '4301 Kirby Dr',
    city: 'Houston',
    state: 'TX',
    zipCode: '77098',
    phone: '(713) 555-3044',
    website: '',
    rating: 4.5,
    reviewCount: 128,
    latitude: 29.7285,
    longitude: -95.4186,
    distanceMiles: 4.3,
    savedAt: undefined,
    createdAt: new Date().toISOString(),
  },
  {
    id: '31',
    businessName: 'Pacific Coast Yard Design',
    category: 'Landscaping',
    address: '818 Stewart St',
    city: 'Seattle',
    state: 'WA',
    zipCode: '98101',
    phone: '(206) 555-3121',
    website: 'https://pacificcoastyarddesign.com',
    rating: 4.7,
    reviewCount: 85,
    latitude: 47.6101,
    longitude: -122.3348,
    distanceMiles: 7.1,
    savedAt: undefined,
    createdAt: new Date().toISOString(),
  },

  // ── Roofing ──────────────────────────────────────────────────────────────────
  {
    id: '32',
    businessName: 'StormShield Roofing & Repair',
    category: 'Roofing',
    address: '6600 E Mockingbird Ln',
    city: 'Dallas',
    state: 'TX',
    zipCode: '75214',
    phone: '(214) 555-3244',
    website: '',
    rating: 4.3,
    reviewCount: 61,
    latitude: 32.8368,
    longitude: -96.7499,
    distanceMiles: 6.4,
    savedAt: undefined,
    createdAt: new Date().toISOString(),
  },
  {
    id: '33',
    businessName: 'Summit Roofing Solutions',
    category: 'Roofing',
    address: '7210 E Colfax Ave',
    city: 'Denver',
    state: 'CO',
    zipCode: '80220',
    phone: '(720) 555-3356',
    website: 'https://summitroofingco.com',
    rating: 4.0,
    reviewCount: 39,
    latitude: 39.7404,
    longitude: -104.9003,
    distanceMiles: 11.8,
    savedAt: undefined,
    createdAt: new Date().toISOString(),
  },

  // ── Moving Companies ─────────────────────────────────────────────────────────
  {
    id: '34',
    businessName: 'First Class Movers NYC',
    category: 'Moving Companies',
    address: '252 W 37th St',
    city: 'New York',
    state: 'NY',
    zipCode: '10018',
    phone: '(212) 555-3422',
    website: '',
    rating: 4.1,
    reviewCount: 193,
    latitude: 40.7529,
    longitude: -73.9948,
    distanceMiles: 2.1,
    savedAt: undefined,
    createdAt: new Date().toISOString(),
  },
  {
    id: '35',
    businessName: 'Biscayne Bay Moving & Storage',
    category: 'Moving Companies',
    address: '3400 NW 7th Ave',
    city: 'Miami',
    state: 'FL',
    zipCode: '33127',
    phone: '(305) 555-3541',
    website: 'https://biscaynemovers.com',
    rating: 3.8,
    reviewCount: 29,
    latitude: 25.7946,
    longitude: -80.2101,
    distanceMiles: 13.2,
    savedAt: undefined,
    createdAt: new Date().toISOString(),
  },
]

export async function searchLeadsMock(params: SearchParams): Promise<SearchResult> {
  await new Promise(r => setTimeout(r, 800)) // simulate API delay

  let results = MOCK_BUSINESSES.map(b => ({
    ...b,
    leadScore: calculateLeadScore(b, params),
    status: 'new' as const,
    notes: '',
    distanceMiles: b.distanceMiles ?? Math.random() * params.radiusMiles,
  }))

  // Filter by category
  if (params.category && params.category !== 'Custom Keyword') {
    results = results.filter(b =>
      b.category.toLowerCase().includes(params.category.toLowerCase().replace(/ & /g, ' '))
    )
  }

  // Filter by keyword
  if (params.keyword) {
    const kw = params.keyword.toLowerCase()
    results = results.filter(b =>
      b.businessName.toLowerCase().includes(kw) ||
      b.category.toLowerCase().includes(kw) ||
      b.address.toLowerCase().includes(kw)
    )
  }

  // Filter by minRating
  if (params.minRating) {
    results = results.filter(b => (b.rating ?? 0) >= params.minRating!)
  }

  // Filter hasWebsite
  if (params.hasWebsite === true) {
    results = results.filter(b => b.website && b.website.trim() !== '')
  }

  // Filter hasPhone
  if (params.hasPhone === true) {
    results = results.filter(b => b.phone && b.phone.trim() !== '')
  }

  // Sort by lead score descending
  results.sort((a, b) => b.leadScore - a.leadScore)

  return { leads: results, total: results.length }
}
