-- Audit reports: shareable public-link snapshots of a lead's digital health.
-- Generated by an agency user from a lead card; shared with the prospect as a
-- cold-outreach door opener at /audit/<slug>.
--
-- Access model:
--   * Owner (authenticated user) can insert/read/update/delete their own rows.
--   * Anyone holding the link can read a report: reports are shared by slug,
--     so a public-read SELECT policy exists for anon (and authenticated, so
--     logged-in visitors can open shared links too). The slug is a long random
--     token; treat it as the capability. NOTE: a permissive SELECT policy means
--     rows are technically listable through the API, so column privileges below
--     hide user_id from anon and nothing sensitive beyond the public business
--     snapshot is stored in the row.
--
-- Idempotent: safe to run more than once.

CREATE TABLE IF NOT EXISTS public.audit_reports (
  id         uuid        DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id    uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  slug       text        NOT NULL UNIQUE,
  lead       jsonb       NOT NULL,  -- snapshot of the lead at generation time
  health     jsonb       NOT NULL,  -- HealthScoreResult {total, pillars, verified}
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.audit_reports ENABLE ROW LEVEL SECURITY;

-- Owner read/write
DROP POLICY IF EXISTS "Owners manage their own audit reports" ON public.audit_reports;
CREATE POLICY "Owners manage their own audit reports"
  ON public.audit_reports FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Public read by link (slug is the capability; queried by slug from the
-- public report page)
DROP POLICY IF EXISTS "Public can read audit reports by link" ON public.audit_reports;
CREATE POLICY "Public can read audit reports by link"
  ON public.audit_reports FOR SELECT
  TO anon, authenticated
  USING (true);

-- Anon may only SELECT, and never sees the owner column.
REVOKE ALL ON public.audit_reports FROM anon;
GRANT SELECT (id, slug, lead, health, created_at) ON public.audit_reports TO anon;

CREATE INDEX IF NOT EXISTS audit_reports_user_id_idx ON public.audit_reports(user_id);
