-- ============================================================================
-- LeadZipp: all pending migrations, in one paste.
--
-- Supabase Dashboard -> SQL Editor -> New query -> paste everything -> Run.
-- Every statement is idempotent and non-destructive, so re-running is safe.
--
-- What this does:
--   1. pipeline            - adds the CRM pipeline columns to saved leads
--   2. audit_reports       - creates the shareable audit report table
--   3. daily_search_counter- tamper-proof daily counter for the fair-use cap
--   4. admin_allowlist     - moves auto-admin emails out of the signup trigger
--   5. lock_usage_counters - stops users editing their own usage counters
-- ============================================================================

begin;

-- ===== 20260812_pipeline.sql =====

-- 20260812_pipeline.sql
-- CRM Pipeline: per-lead sales stage on the saved leads table.
--
-- Adds two columns used by the Pipeline board on /saved:
--   pipeline_stage   - one of: new | contacted | replied | meeting | proposal | won | lost
--                      (validated server-side in /api/leads/pipeline; no CHECK constraint so
--                      future stage additions never need a migration)
--   stage_updated_at - when the lead last moved between stages
--
-- Idempotent and non-destructive: safe to run on a fresh or existing database.
-- Run in Supabase: Dashboard -> SQL Editor -> New query -> paste + run.

alter table if exists public.leads
  add column if not exists pipeline_stage   text not null default 'new',
  add column if not exists stage_updated_at timestamptz;

-- Board loads are always "this user's leads grouped by stage"
create index if not exists leads_user_stage_idx
  on public.leads (user_id, pipeline_stage);

-- ===== 20260812_audit_reports.sql =====

-- Audit reports: shareable public-link snapshots of a lead's digital health.
-- Generated by an agency user from a lead card; shared with the prospect as a
-- cold-outreach door opener at /audit/<slug>.
--
-- Access model:
--   * Owner (authenticated user) can insert/read/update/delete their own rows.
--   * Anyone holding the link can read a report, but ONLY through the server:
--     /audit/[slug] fetches the row with the service role key, which bypasses
--     RLS. The slug is the capability.
--
--     There is deliberately NO anon SELECT policy. A permissive
--     "FOR SELECT TO anon USING (true)" policy would have made every report
--     listable through PostgREST, letting anyone enumerate which businesses
--     every customer is prospecting. That prospect list is the customer's
--     competitive advantage, so the table is not exposed to anon at all and
--     anon's table privileges are revoked outright.
--
-- Idempotent: safe to run more than once.

CREATE TABLE IF NOT EXISTS public.audit_reports (
  id         uuid        DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id    uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  slug       text        NOT NULL UNIQUE,
  lead       jsonb       NOT NULL,  -- snapshot of the lead at generation time
  health     jsonb       NOT NULL,  -- HealthScoreResult {total, pillars, verified}
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.audit_reports ENABLE ROW LEVEL SECURITY;

-- Owner read/write
DROP POLICY IF EXISTS "Owners manage their own audit reports" ON public.audit_reports;
CREATE POLICY "Owners manage their own audit reports"
  ON public.audit_reports FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Public sharing is served by the service role in the /audit/[slug] route, not
-- by a policy. Drop the enumerable policy if an earlier run of this file
-- created it.
DROP POLICY IF EXISTS "Public can read audit reports by link" ON public.audit_reports;

-- anon gets no access to this table at all.
REVOKE ALL ON public.audit_reports FROM anon;

CREATE INDEX IF NOT EXISTS audit_reports_user_id_idx ON public.audit_reports(user_id);

-- ===== 20260812_daily_search_counter.sql =====

-- Tamper-proof daily search counter.
--
-- The paid fair-use cap (150 live searches/day) counted rows in
-- search_history. But DELETE /api/history lets a user clear their own history,
-- and it runs with the service role, so any paid user could reset the cap by
-- clearing history between batches and then run unlimited billable Google
-- Places searches. The counter and the user-clearable UI history were the same
-- table, which is the bug.
--
-- This moves the count onto usage_limits, which users can read but never write
-- (see 20260812_lock_usage_counters.sql). Clearing search history no longer
-- touches billing enforcement.
--
-- Idempotent and non-destructive: safe to run more than once.

alter table if exists public.usage_limits
  add column if not exists searches_today      integer not null default 0,
  add column if not exists searches_today_date date;

-- Increments the caller's daily counter, rolling over automatically on the
-- first search of a new UTC day. SECURITY DEFINER so it still works once
-- direct writes to usage_limits are locked down.
--
-- The uid argument is NOT trusted. A SECURITY DEFINER function that acts on a
-- caller-supplied user id lets any authenticated user inflate a stranger's
-- counter and lock them out of search. When a session is present we always use
-- auth.uid() and ignore the argument; the argument is honored only when
-- auth.uid() is null, which means the caller is the service role.
create or replace function public.increment_daily_searches(uid uuid)
returns integer as $$
declare
  new_count integer;
  target_id uuid := coalesce(auth.uid(), uid);
begin
  if target_id is null then
    return 0;
  end if;

  update public.usage_limits
  set
    searches_today = case
      when searches_today_date is distinct from (now() at time zone 'utc')::date then 1
      else searches_today + 1
    end,
    searches_today_date = (now() at time zone 'utc')::date,
    searches_this_month = searches_this_month + 1,
    updated_at = now()
  where user_id = target_id
  returning searches_today into new_count;

  return coalesce(new_count, 0);
end;
$$ language plpgsql security definer
set search_path = public, pg_temp;

revoke all on function public.increment_daily_searches(uuid) from public, anon;
grant execute on function public.increment_daily_searches(uuid) to authenticated, service_role;

-- Same hardening for the pre-existing monthly counter, which had the identical
-- flaw: any authenticated user could call it with someone else's uid and burn
-- through that user's monthly search allowance.
create or replace function public.increment_searches(uid uuid)
returns void as $$
declare
  target_id uuid := coalesce(auth.uid(), uid);
begin
  if target_id is null then
    return;
  end if;

  update public.usage_limits
  set
    searches_this_month = searches_this_month + 1,
    updated_at = now()
  where user_id = target_id;
end;
$$ language plpgsql security definer
set search_path = public, pg_temp;

revoke all on function public.increment_searches(uuid) from public, anon;
grant execute on function public.increment_searches(uuid) to authenticated, service_role;

-- ===== 20260812_admin_allowlist.sql =====

-- Move the auto-admin list out of the signup trigger's source code.
--
-- handle_new_user() hardcoded two email addresses that receive
-- role='admin', plan='agency' automatically on signup. Two problems:
--   1. Anyone who can register that address inherits the admin panel. The
--      addresses are dormant while the accounts exist, but a deleted account
--      or a recycled address re-arms the grant silently.
--   2. Revoking an admin required a code change and a migration, so the live
--      grant list was invisible to anyone reading the app.
--
-- The list becomes a locked-down table instead: service-role only, readable by
-- nobody through the API. Existing admins are seeded first, so this migration
-- cannot lock the owner out. Removing an admin is now a DELETE, not a deploy.
--
-- Idempotent and non-destructive: safe to run more than once.

create table if not exists public.admin_allowlist (
  email      text primary key,
  note       text,
  created_at timestamptz not null default now()
);

alter table public.admin_allowlist enable row level security;

-- No policies are defined on purpose. With RLS on and zero policies, anon and
-- authenticated callers can do nothing; the service role bypasses RLS. Revoke
-- the table grants too, so the allowlist never appears through PostgREST.
revoke all on public.admin_allowlist from anon, authenticated;

-- Seed the addresses that are already admins so behavior is unchanged today.
insert into public.admin_allowlist (email, note)
values
  ('scarface572011@live.com', 'Owner account, migrated from hardcoded trigger'),
  ('jezdangomez@gmail.com',   'Owner account, migrated from hardcoded trigger')
on conflict (email) do nothing;

-- Trigger now consults the table rather than a literal list.
create or replace function public.handle_new_user()
returns trigger as $$
declare
  v_role text := 'user';
  v_plan text := 'free';
begin
  if exists (
    select 1 from public.admin_allowlist
    where email = lower(new.email)
  ) then
    v_role := 'admin';
    v_plan := 'agency';
  end if;

  insert into public.users_profile (id, email, full_name, role, plan)
  values (new.id, new.email, new.raw_user_meta_data->>'full_name', v_role, v_plan);

  insert into public.usage_limits (user_id) values (new.id);

  return new;
end;
$$ language plpgsql security definer
set search_path = public, pg_temp;

-- To revoke an admin later:
--   delete from public.admin_allowlist where email = 'someone@example.com';
--   update public.users_profile set role = 'user', plan = 'free'
--     where lower(email) = 'someone@example.com';
--
-- To audit who is currently privileged:
--   select email, role, plan from public.users_profile where role = 'admin';

-- ===== 20260812_lock_usage_counters.sql =====

-- 20260812_lock_usage_counters.sql
-- Stop users from resetting their own metering to bypass search caps.
--
-- AUDIT (confirmed live 2026-08-12): usage_limits and search_history were
-- created (schema.sql) with `for all using (auth.uid() = user_id)` policies,
-- so a logged-in user could, with the public anon key + their own session:
--   update usage_limits set searches_this_month = 0 where user_id = <self>   -- reset free cap
--   delete from search_history where user_id = <self>                        -- reset daily fair-use cap
-- Both were verified returning HTTP 200. This defeats the free monthly cap
-- (25) and the paid daily fair-use cap (150), feeding the Google/Hunter bill.
--
-- FIX: users may SELECT their own rows; only the service role writes them.
--   - usage_limits: SELECT only for users. The increment_searches() RPC is
--     SECURITY DEFINER, and the app's write paths use the service-role client,
--     so counting still works. Users can no longer zero their counter.
--   - search_history: SELECT + INSERT for users (the app inserts one row per
--     billable search), but NO UPDATE/DELETE, so a user can't delete today's
--     rows to reset the daily fair-use count.
--
-- ── WHY THE DROPS ARE DONE BY QUERYING pg_policies ──────────────────────────
-- Postgres ORs permissive policies together. A leftover permissive
-- `FOR ALL USING (auth.uid() = user_id)` policy therefore keeps granting
-- UPDATE and DELETE no matter how restrictive the new SELECT-only policies
-- are: adding a policy can only widen access, never narrow it. The only way
-- to lock these tables down is to remove the old policy, and
-- `drop policy if exists "<name>"` is a SILENT no-op when the name is wrong.
--
-- The first version of this migration dropped guessed names
-- ("Users can view their own usage", "Users can manage their own search
-- history") that do not exist. The names actually created by
-- supabase/schema.sql are:
--   * "Users can view own usage limits"     on usage_limits   (FOR ALL, ~137-139)
--   * "Users can manage own search history" on search_history (FOR ALL, ~132-134)
-- So the earlier run dropped nothing and the FOR ALL policies survived.
--
-- Rather than trade one hardcoded guess for another, the blocks below drop
-- EVERY existing policy on the two tables by reading pg_policies, then create
-- exactly the intended ones. That is correct whether or not the earlier
-- version already ran, and it cannot drift again if a policy is renamed.
-- Nothing else needs a policy here: the service role bypasses RLS entirely,
-- and admin reads of these tables go through the service-role client.
--
-- Idempotent and safe to re-run. Run in Supabase: Dashboard (project
-- Leadzip-prod, ref oeotgkarnqrfvvdfnaya) -> SQL Editor -> paste + run.
-- RUN 20260810_security_and_integrity.sql FIRST (it blocks plan/role/status
-- self-escalation, the more severe hole).

-- ── usage_limits: read-only for users, service-role writes only ─────────────
alter table public.usage_limits enable row level security;

do $$
declare
  pol record;
begin
  for pol in
    select policyname
    from pg_policies
    where schemaname = 'public' and tablename = 'usage_limits'
  loop
    execute format('drop policy %I on public.usage_limits', pol.policyname);
  end loop;
end $$;

create policy "usage_limits_select_own"
  on public.usage_limits for select
  to authenticated
  using (auth.uid() = user_id);

-- ── search_history: users may read and insert, but never update or delete ───
alter table public.search_history enable row level security;

do $$
declare
  pol record;
begin
  for pol in
    select policyname
    from pg_policies
    where schemaname = 'public' and tablename = 'search_history'
  loop
    execute format('drop policy %I on public.search_history', pol.policyname);
  end loop;
end $$;

create policy "search_history_select_own"
  on public.search_history for select
  to authenticated
  using (auth.uid() = user_id);

create policy "search_history_insert_own"
  on public.search_history for insert
  to authenticated
  with check (auth.uid() = user_id);

-- ── subscriptions: one row per user, so the webhook + checkout-return
--    activation can't race into two rows (which then 500s every future sub
--    webhook). Safe if no duplicates exist yet (true on a fresh billing table).
create unique index if not exists subscriptions_user_id_key
  on public.subscriptions (user_id);

-- ── Verification: expect exactly the three policies created above, and no
--    UPDATE/DELETE/ALL row for either table.
select tablename, policyname, cmd, roles, qual, with_check
from pg_policies
where schemaname = 'public'
  and tablename in ('usage_limits', 'search_history')
order by tablename, policyname;

commit;
