-- LeadZipp: run both pending migrations in one paste.
-- Supabase Dashboard -> SQL Editor -> New query -> paste all -> Run.
-- Idempotent and non-destructive: safe to run more than once.

begin;

-- 20260812_pipeline.sql
-- CRM Pipeline: per-lead sales stage on the saved leads table.
--
-- Adds two columns used by the Pipeline board on /saved:
--   pipeline_stage   - one of: new | contacted | replied | meeting | proposal | won | lost
--                      (validated server-side in /api/leads/pipeline; no CHECK constraint so
--                      future stage additions never need a migration)
--   stage_updated_at - when the lead last moved between stages
--
-- Idempotent and non-destructive: safe to run on a fresh or existing database.
-- Run in Supabase: Dashboard -> SQL Editor -> New query -> paste + run.

alter table if exists public.leads
  add column if not exists pipeline_stage   text not null default 'new',
  add column if not exists stage_updated_at timestamptz;

-- Board loads are always "this user's leads grouped by stage"
create index if not exists leads_user_stage_idx
  on public.leads (user_id, pipeline_stage);

-- Audit reports: shareable public-link snapshots of a lead's digital health.
-- Generated by an agency user from a lead card; shared with the prospect as a
-- cold-outreach door opener at /audit/<slug>.
--
-- Access model:
--   * Owner (authenticated user) can insert/read/update/delete their own rows.
--   * Anyone holding the link can read a report, but ONLY through the server:
--     /audit/[slug] fetches the row with the service role key, which bypasses
--     RLS. The slug is the capability.
--
--     There is deliberately NO anon SELECT policy. A permissive
--     "FOR SELECT TO anon USING (true)" policy would have made every report
--     listable through PostgREST, letting anyone enumerate which businesses
--     every customer is prospecting. That prospect list is the customer's
--     competitive advantage, so the table is not exposed to anon at all and
--     anon's table privileges are revoked outright.
--
-- Idempotent: safe to run more than once.

CREATE TABLE IF NOT EXISTS public.audit_reports (
  id         uuid        DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id    uuid        NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  slug       text        NOT NULL UNIQUE,
  lead       jsonb       NOT NULL,  -- snapshot of the lead at generation time
  health     jsonb       NOT NULL,  -- HealthScoreResult {total, pillars, verified}
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.audit_reports ENABLE ROW LEVEL SECURITY;

-- Owner read/write
DROP POLICY IF EXISTS "Owners manage their own audit reports" ON public.audit_reports;
CREATE POLICY "Owners manage their own audit reports"
  ON public.audit_reports FOR ALL
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Public sharing is served by the service role in the /audit/[slug] route, not
-- by a policy. Drop the enumerable policy if an earlier run of this file
-- created it.
DROP POLICY IF EXISTS "Public can read audit reports by link" ON public.audit_reports;

-- anon gets no access to this table at all.
REVOKE ALL ON public.audit_reports FROM anon;

CREATE INDEX IF NOT EXISTS audit_reports_user_id_idx ON public.audit_reports(user_id);

commit;
